### PR TITLE
Adds program schedule

### PR DESCRIPTION
**Pull request by dbollinger**
Need updated titles, and some better styling

### CODE REVIEW

**Comment by dbollinger** [comment]
screen shot 2018-08-14 at 10 12 30 pm

**Comment by dbollinger** [comment]
screen shot 2018-08-18 at 3 21 29 pm
screen shot 2018-08-18 at 3 21 26 pm

**Comment by EndangeredMassa** [comment]
Speakers: Looks good!

Schedule: I think we can follow the same layout as the speakers to put the title, description, and speaker photo/name in a list.

**Comment by MelSumner** [comment]
Could we try something like this? https://codepen.io/melsumner/pen/zJOqQV?editors=1100

**Pull request merged**
